on:
  pull_request_target:
  push:
    branches:
      - 1.x

jobs:
  validate:
    name: Composer Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: composer validate
